export const pokeTypes: { [index: PropertyKey]: string } = {
  bug: '../../assets/Bug_Type_Icon.svg',
  dark: '../../assets/Dark_Type_Icon.svg',
  dragon: '../../assets/Dragon_Type_Icon.svg',
  electric: '../../assets/Electric_Type_Icon.svg',
  fairy: '../../assets/Fairy_Type_Icon.svg',
  fighting: '../../assets/Fighting_Type_Icon.svg',
  fire: '../../assets/Fire_Type_Icon.svg',
  flying: '../../assets/Flying_Type_Icon.svg',
  ghost: '../../assets/Ghost_Type_Icon.svg',
  grass: '../../assets/Grass_Type_Icon.svg',
  ground: '../../assets/Ground_Type_Icon.svg',
  ice: '../../assets/Ice_Type_Icon.svg',
  normal: '../../assets/Normal_Type_Icon.svg',
  poison: '../../assets/Poison_Type_Icon.svg',
  psychic: '../../assets/Psychic_Type_Icon.svg',
  rock: '../../assets/Rock_Type_Icon.svg',
  steel: '../../assets/Steel_Type_Icon.svg',
  water: '../../assets/Water_Type_Icon.svg',
};

export const typeColors: { [index: PropertyKey]: string } = {
  bug: '#83C300',
  dark: '#5B5466',
  dragon: '#006FC9',
  electric: '#FBD100',
  fairy: '#FB89EB',
  fighting: '#E0306A',
  fire: '#FF9741',
  flying: '#89AAE3',
  ghost: '#4C6AB2',
  grass: '#38BF4B',
  ground: '#E87236',
  ice: '#4CD1C0',
  normal: '#919AA2',
  poison: '#B567CE',
  psychic: '#FF6675',
  rock: '#C8B686',
  steel: '#5A8EA2',
  water: '#3692DC',
};
