export const pokeTypes: { [index: PropertyKey]: string } = {
  bug: '../../assets/Bug_Type_Icon.svg',
  dark: '../../assets/Dark_Type_Icon.svg',
  dragon: '../../assets/Dragon_Type_Icon.svg',
  electric: '../../assets/Electric_Type_Icon.svg',
  fairy: '../../assets/fairy_Type_Icon.svg',
  fighting: '../../assets/Fighting_Type_Icon.svg',
  fire: '../../assets/Fire_Type_Icon.svg',
  flying: '../../assets/Flying_Type_Icon.svg',
  ghost: '../../assets/Ghost_Type_Icon.svg',
  grass: '../../assets/Grass_Type_Icon.svg',
  ground: '../../assets/Ground_Type_Icon.svg',
  ice: '../../assets/Ice_Type_Icon.svg',
  normal: '../../assets/Normal_Type_Icon.svg',
  poison: '../../assets/Poison_Type_Icon.svg',
  psychic: '../../assets/Psychic_Type_Icon.svg',
  rock: '../../assets/Rock_Type_Icon.svg',
  steel: '../../assets/Steel_Type_Icon.svg',
  water: '../../assets/Water_Type_Icon.svg',
};
